language: python
python:     
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
after_success:
  - codecov # submit coverage